# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_main.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTableWidget,
    QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.DownloadButton = QPushButton(self.centralwidget)
        self.DownloadButton.setObjectName(u"DownloadButton")
        self.DownloadButton.setGeometry(QRect(20, 0, 211, 61))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        self.DownloadButton.setFont(font)
        self.InfoTable = QTextEdit(self.centralwidget)
        self.InfoTable.setObjectName(u"InfoTable")
        self.InfoTable.setGeometry(QRect(880, 10, 221, 61))
        self.InfoTable.setFont(font)
        self.InfoTable.setReadOnly(True)
        self.OpenDicomButton = QPushButton(self.centralwidget)
        self.OpenDicomButton.setObjectName(u"OpenDicomButton")
        self.OpenDicomButton.setEnabled(False)
        self.OpenDicomButton.setGeometry(QRect(240, 0, 161, 61))
        self.OpenDicomButton.setFont(font)
        self.AxialImage = QLabel(self.centralwidget)
        self.AxialImage.setObjectName(u"AxialImage")
        self.AxialImage.setGeometry(QRect(20, 200, 350, 350))
        self.AxialImage.setFont(font)
        self.AxialImage.setAutoFillBackground(True)
        self.AxialImage.setTextFormat(Qt.PlainText)
        self.AxialImage.setScaledContents(True)
        self.AxialImage.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.AxialImage.setWordWrap(False)
        self.SagitalImage = QLabel(self.centralwidget)
        self.SagitalImage.setObjectName(u"SagitalImage")
        self.SagitalImage.setGeometry(QRect(20, 670, 350, 350))
        self.SagitalImage.setFont(font)
        self.SagitalImage.setAutoFillBackground(True)
        self.SagitalImage.setTextFormat(Qt.PlainText)
        self.SagitalImage.setScaledContents(True)
        self.SagitalImage.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.SagitalImage.setWordWrap(False)
        self.CoronalImage = QLabel(self.centralwidget)
        self.CoronalImage.setObjectName(u"CoronalImage")
        self.CoronalImage.setGeometry(QRect(390, 670, 350, 350))
        self.CoronalImage.setFont(font)
        self.CoronalImage.setAutoFillBackground(True)
        self.CoronalImage.setTextFormat(Qt.PlainText)
        self.CoronalImage.setScaledContents(True)
        self.CoronalImage.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.CoronalImage.setWordWrap(False)
        self.SagitalSlider = QSlider(self.centralwidget)
        self.SagitalSlider.setObjectName(u"SagitalSlider")
        self.SagitalSlider.setGeometry(QRect(20, 630, 301, 22))
        self.SagitalSlider.setMinimum(1)
        self.SagitalSlider.setMaximum(512)
        self.SagitalSlider.setOrientation(Qt.Horizontal)
        self.SagitalCount = QTextEdit(self.centralwidget)
        self.SagitalCount.setObjectName(u"SagitalCount")
        self.SagitalCount.setGeometry(QRect(330, 630, 41, 31))
        self.SagitalCount.setFont(font)
        self.SagitalCount.setReadOnly(True)
        self.CoronalCount = QTextEdit(self.centralwidget)
        self.CoronalCount.setObjectName(u"CoronalCount")
        self.CoronalCount.setGeometry(QRect(700, 630, 41, 31))
        self.CoronalCount.setFont(font)
        self.CoronalCount.setReadOnly(True)
        self.CoronalSlider = QSlider(self.centralwidget)
        self.CoronalSlider.setObjectName(u"CoronalSlider")
        self.CoronalSlider.setGeometry(QRect(390, 630, 301, 22))
        self.CoronalSlider.setMinimum(1)
        self.CoronalSlider.setMaximum(512)
        self.CoronalSlider.setOrientation(Qt.Horizontal)
        self.AxialCount = QTextEdit(self.centralwidget)
        self.AxialCount.setObjectName(u"AxialCount")
        self.AxialCount.setGeometry(QRect(330, 160, 41, 31))
        self.AxialCount.setFont(font)
        self.AxialCount.setReadOnly(True)
        self.AxialSlider = QSlider(self.centralwidget)
        self.AxialSlider.setObjectName(u"AxialSlider")
        self.AxialSlider.setGeometry(QRect(20, 160, 301, 22))
        self.AxialSlider.setMinimum(1)
        self.AxialSlider.setMaximum(512)
        self.AxialSlider.setOrientation(Qt.Horizontal)
        self.tableDidcom = QTableWidget(self.centralwidget)
        if (self.tableDidcom.columnCount() < 2):
            self.tableDidcom.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableDidcom.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableDidcom.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableDidcom.setObjectName(u"tableDidcom")
        self.tableDidcom.setGeometry(QRect(880, 140, 241, 192))
        self.tableDidcom.setFont(font)
        self.tableDidcom.setShowGrid(True)
        self.AddEntryButton = QPushButton(self.centralwidget)
        self.AddEntryButton.setObjectName(u"AddEntryButton")
        self.AddEntryButton.setGeometry(QRect(880, 340, 241, 41))
        self.AddEntryButton.setFont(font)
        self.ScanObjectLabel = QLabel(self.centralwidget)
        self.ScanObjectLabel.setObjectName(u"ScanObjectLabel")
        self.ScanObjectLabel.setGeometry(QRect(880, 380, 241, 31))
        self.ScanObjectLabel.setFont(font)
        self.ScanObjectLine = QLineEdit(self.centralwidget)
        self.ScanObjectLine.setObjectName(u"ScanObjectLine")
        self.ScanObjectLine.setGeometry(QRect(880, 410, 241, 31))
        self.ScanObjectLine.setFont(font)
        self.FullNameLabel = QLabel(self.centralwidget)
        self.FullNameLabel.setObjectName(u"FullNameLabel")
        self.FullNameLabel.setGeometry(QRect(880, 440, 241, 31))
        self.FullNameLabel.setFont(font)
        self.FullNametLine = QLineEdit(self.centralwidget)
        self.FullNametLine.setObjectName(u"FullNametLine")
        self.FullNametLine.setGeometry(QRect(880, 470, 241, 31))
        self.FullNametLine.setFont(font)
        self.TreatmentLabel = QLabel(self.centralwidget)
        self.TreatmentLabel.setObjectName(u"TreatmentLabel")
        self.TreatmentLabel.setGeometry(QRect(880, 500, 241, 31))
        self.TreatmentLabel.setFont(font)
        self.TreatmentLine = QLineEdit(self.centralwidget)
        self.TreatmentLine.setObjectName(u"TreatmentLine")
        self.TreatmentLine.setGeometry(QRect(880, 530, 241, 31))
        self.TreatmentLine.setFont(font)
        self.DirectionLine = QLineEdit(self.centralwidget)
        self.DirectionLine.setObjectName(u"DirectionLine")
        self.DirectionLine.setGeometry(QRect(880, 590, 241, 31))
        self.DirectionLine.setFont(font)
        self.DirectionLabel = QLabel(self.centralwidget)
        self.DirectionLabel.setObjectName(u"DirectionLabel")
        self.DirectionLabel.setGeometry(QRect(880, 560, 241, 31))
        self.DirectionLabel.setFont(font)
        self.ReccomendationLine = QLineEdit(self.centralwidget)
        self.ReccomendationLine.setObjectName(u"ReccomendationLine")
        self.ReccomendationLine.setGeometry(QRect(880, 650, 241, 31))
        self.ReccomendationLine.setFont(font)
        self.ReccomendationLabel = QLabel(self.centralwidget)
        self.ReccomendationLabel.setObjectName(u"ReccomendationLabel")
        self.ReccomendationLabel.setGeometry(QRect(880, 620, 241, 31))
        self.ReccomendationLabel.setFont(font)
        self.OpenDataBaseButton = QPushButton(self.centralwidget)
        self.OpenDataBaseButton.setObjectName(u"OpenDataBaseButton")
        self.OpenDataBaseButton.setGeometry(QRect(1360, 10, 231, 61))
        self.OpenDataBaseButton.setFont(font)
        self.DataBaseTable = QTableWidget(self.centralwidget)
        self.DataBaseTable.setObjectName(u"DataBaseTable")
        self.DataBaseTable.setGeometry(QRect(1360, 140, 541, 541))
        self.DataBaseTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.BackTableButton = QPushButton(self.centralwidget)
        self.BackTableButton.setObjectName(u"BackTableButton")
        self.BackTableButton.setGeometry(QRect(1360, 700, 121, 41))
        self.BackTableButton.setFont(font)
        self.DeleteTableLine = QLineEdit(self.centralwidget)
        self.DeleteTableLine.setObjectName(u"DeleteTableLine")
        self.DeleteTableLine.setGeometry(QRect(1640, 700, 121, 41))
        self.DeleteTableButton = QPushButton(self.centralwidget)
        self.DeleteTableButton.setObjectName(u"DeleteTableButton")
        self.DeleteTableButton.setGeometry(QRect(1780, 700, 121, 41))
        self.DeleteTableButton.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.DownloadButton.setText(QCoreApplication.translate("MainWindow", u"Download Dicom", None))
        self.OpenDicomButton.setText(QCoreApplication.translate("MainWindow", u"Open Dicom", None))
        self.AxialImage.setText(QCoreApplication.translate("MainWindow", u"Axial Image", None))
        self.SagitalImage.setText(QCoreApplication.translate("MainWindow", u"Sagital Image", None))
        self.CoronalImage.setText(QCoreApplication.translate("MainWindow", u"Coronal Image", None))
        ___qtablewidgetitem = self.tableDidcom.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Parameter", None));
        ___qtablewidgetitem1 = self.tableDidcom.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Value", None));
        self.AddEntryButton.setText(QCoreApplication.translate("MainWindow", u"Add Entry", None))
        self.ScanObjectLabel.setText(QCoreApplication.translate("MainWindow", u"Write a scan object:", None))
        self.FullNameLabel.setText(QCoreApplication.translate("MainWindow", u"Write a full name:", None))
        self.TreatmentLabel.setText(QCoreApplication.translate("MainWindow", u"Write a treatment:", None))
        self.DirectionLabel.setText(QCoreApplication.translate("MainWindow", u"Write a direction:", None))
        self.ReccomendationLabel.setText(QCoreApplication.translate("MainWindow", u"Write a reccomendation:", None))
        self.OpenDataBaseButton.setText(QCoreApplication.translate("MainWindow", u"Open DataBase", None))
        self.BackTableButton.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.DeleteTableButton.setText(QCoreApplication.translate("MainWindow", u"Back", None))
    # retranslateUi

